// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebServiceProject.Persistence;

namespace WebServiceProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200603185452_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebServiceProject.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoCount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasMaxLength(50);

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YesCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Çok hızlı ve güvenilir sipariş teşekkürler direnc.net",
                            NoCount = 2,
                            ProductId = 1,
                            Star = 5,
                            Title = "KODLAMA",
                            YesCount = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ürün çok güzel tavsiye ederim",
                            NoCount = 3,
                            ProductId = 1,
                            Star = 5,
                            Title = " Kalite",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 3,
                            Description = "Çok beğendim satıcı ilgili ve hızlı geldi eksiksiz geldi yorumlara bakarak aldım ve pişman olmadım. Yorum yaparak insanlara yardımcı olmak lazım ",
                            NoCount = 2,
                            ProductId = 1,
                            Star = 4,
                            Title = "Ürün",
                            YesCount = 5
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cok tereddüt ederek sipariş verdim.Satıcı çok ilgili, ürünün aciliyetini bildirdim, 24 saat dolmadan,eksiksiz ve hızlı bir sekile ulaştı, ürün de gayet ideal, çok beğendim,tesekkürler.. ",
                            NoCount = 3,
                            ProductId = 2,
                            Star = 5,
                            Title = "Hizmet ",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 5,
                            Description = "fiyatina gore iyi bir cihaz. tavsiye ederim",
                            NoCount = 1,
                            ProductId = 2,
                            Star = 3,
                            Title = "Kalite ",
                            YesCount = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ürün gayet güzel mağazanın hizmeti mükemmel anında hızlı Kargo yapıldı bir gün sonra ürün elime ulaştı paketi de gayet özenliydi teşekkür ederim ",
                            NoCount = 3,
                            ProductId = 3,
                            Star = 5,
                            Title = " KAliteli Hızlı Hizmet",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ürüne olumsuz yorum yapanlar tekrar baksın ürün gayet sıkıntısı ve hızlı geldi teşekkürler",
                            NoCount = 2,
                            ProductId = 3,
                            Star = 4,
                            Title = " Hizmet",
                            YesCount = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ürün çok kötü paketlenmiş kutusu ezik geldi",
                            NoCount = 6,
                            ProductId = 3,
                            Star = 3,
                            Title = "Kargo",
                            YesCount = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ürün için biraz çekincelerim vardı ama ürün gayet güzel!!",
                            NoCount = 3,
                            ProductId = 4,
                            Star = 4,
                            Title = "Kalite",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 10,
                            Description = "Çok hızlı ve güvenilir sipariş teşekkürler direnc.net",
                            NoCount = 3,
                            ProductId = 4,
                            Star = 4,
                            Title = "KODLAMA",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 11,
                            Description = "Ürün fotoğraftaki gibi gelmedi almanızı tavsiye etmem ",
                            NoCount = 10,
                            ProductId = 4,
                            Star = 4,
                            Title = "Ürün",
                            YesCount = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Cok tereddüt ederek sipariş verdim.Satıcı çok ilgili, ürünün aciliyetini bildirdim, 24 saat dolmadan,eksiksiz ve hızlı bir sekile ulaştı, ürün de gayet ideal, çok beğendim,tesekkürler.. ",
                            NoCount = 3,
                            ProductId = 6,
                            Star = 5,
                            Title = "Hizmet ",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 13,
                            Description = "fiyatina gore iyi bir cihaz. tavsiye ederim",
                            NoCount = 1,
                            ProductId = 6,
                            Star = 3,
                            Title = "Kalite ",
                            YesCount = 4
                        },
                        new
                        {
                            Id = 14,
                            Description = "Ürüne olumsuz yorum yapanlar tekrar baksın ürün gayet sıkıntısı ve hızlı geldi teşekkürler",
                            NoCount = 2,
                            ProductId = 8,
                            Star = 4,
                            Title = " Hizmet",
                            YesCount = 4
                        },
                        new
                        {
                            Id = 15,
                            Description = "Ürün gayet güzel mağazanın hizmeti mükemmel anında hızlı Kargo yapıldı bir gün sonra ürün elime ulaştı paketi de gayet özenliydi teşekkür ederim ",
                            NoCount = 3,
                            ProductId = 3,
                            Star = 5,
                            Title = " KAliteli Hızlı Hizmet",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 16,
                            Description = "Çok hızlı ve güvenilir sipariş teşekkürler direnc.net",
                            NoCount = 2,
                            ProductId = 8,
                            Star = 5,
                            Title = "KODLAMA",
                            YesCount = 3
                        },
                        new
                        {
                            Id = 17,
                            Description = "Çok hızlı ve güvenilir sipariş teşekkürler direnc.net",
                            NoCount = 2,
                            ProductId = 10,
                            Star = 5,
                            Title = "KODLAMA",
                            YesCount = 3
                        },
                        new
                        {
                            Id = 18,
                            Description = "Ürün çok güzel tavsiye ederim",
                            NoCount = 3,
                            ProductId = 10,
                            Star = 5,
                            Title = " Kalite",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 19,
                            Description = "fiyatina gore iyi bir cihaz. tavsiye ederim",
                            NoCount = 1,
                            ProductId = 10,
                            Star = 2,
                            Title = "Kalite ",
                            YesCount = 5
                        },
                        new
                        {
                            Id = 20,
                            Description = "Ürün gayet güzel mağazanın hizmeti mükemmel anında hızlı Kargo yapıldı bir gün sonra ürün elime ulaştı paketi de gayet özenliydi teşekkür ederim ",
                            NoCount = 3,
                            ProductId = 13,
                            Star = 5,
                            Title = " KAliteli Hızlı Hizmet",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 21,
                            Description = "Çok hızlı ve güvenilir sipariş teşekkürler direnc.net",
                            NoCount = 2,
                            ProductId = 13,
                            Star = 5,
                            Title = "KODLAMA",
                            YesCount = 3
                        },
                        new
                        {
                            Id = 22,
                            Description = "ürün çok kötü sakın almayın ",
                            NoCount = 10,
                            ProductId = 13,
                            Star = 5,
                            Title = " Kalite",
                            YesCount = 1
                        },
                        new
                        {
                            Id = 23,
                            Description = "Ürün fotoğraftaki gibi gelmedi almanızı tavsiye etmem ",
                            NoCount = 10,
                            ProductId = 16,
                            Star = 2,
                            Title = "Ürün",
                            YesCount = 2
                        },
                        new
                        {
                            Id = 24,
                            Description = "Cok tereddüt ederek sipariş verdim.Satıcı çok ilgili, ürünün aciliyetini bildirdim, 24 saat dolmadan,eksiksiz ve hızlı bir sekile ulaştı, ürün de gayet ideal, çok beğendim,tesekkürler.. ",
                            NoCount = 3,
                            ProductId = 16,
                            Star = 3,
                            Title = "Hizmet ",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 25,
                            Description = "Ürün gayet güzel mağazanın hizmeti mükemmel anında hızlı Kargo yapıldı bir gün sonra ürün elime ulaştı paketi de gayet özenliydi teşekkür ederim ",
                            NoCount = 4,
                            ProductId = 18,
                            Star = 5,
                            Title = " KAliteli Hızlı Hizmet",
                            YesCount = 12
                        },
                        new
                        {
                            Id = 26,
                            Description = "Cok tereddüt ederek sipariş verdim.Satıcı çok ilgili, ürünün aciliyetini bildirdim, 24 saat dolmadan,eksiksiz ve hızlı bir sekile ulaştı, ürün de gayet ideal, çok beğendim,tesekkürler.. ",
                            NoCount = 5,
                            ProductId = 18,
                            Star = 5,
                            Title = "Hizmet ",
                            YesCount = 2
                        },
                        new
                        {
                            Id = 27,
                            Description = "ürün çok kötü sakın almayın  ",
                            NoCount = 3,
                            ProductId = 18,
                            Star = 5,
                            Title = "Hizmet ",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 28,
                            Description = "Çok hızlı ve güvenilir sipariş teşekkürler direnc.net",
                            NoCount = 2,
                            ProductId = 21,
                            Star = 5,
                            Title = "KODLAMA",
                            YesCount = 3
                        },
                        new
                        {
                            Id = 29,
                            Description = "Ürün çok güzel tavsiye ederim",
                            NoCount = 3,
                            ProductId = 21,
                            Star = 5,
                            Title = " Kalite",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 30,
                            Description = "Çok beğendim satıcı ilgili ve hızlı geldi eksiksiz geldi yorumlara bakarak aldım ve pişman olmadım. Yorum yaparak insanlara yardımcı olmak lazım ",
                            NoCount = 2,
                            ProductId = 21,
                            Star = 4,
                            Title = "Ürün",
                            YesCount = 5
                        },
                        new
                        {
                            Id = 31,
                            Description = "Cok tereddüt ederek sipariş verdim.Satıcı çok ilgili, ürünün aciliyetini bildirdim, 24 saat dolmadan,eksiksiz ve hızlı bir sekile ulaştı, ürün de gayet ideal, çok beğendim,tesekkürler.. ",
                            NoCount = 3,
                            ProductId = 22,
                            Star = 5,
                            Title = "Hizmet ",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 32,
                            Description = "fiyatina gore iyi bir cihaz. tavsiye ederim",
                            NoCount = 1,
                            ProductId = 22,
                            Star = 3,
                            Title = "Kalite ",
                            YesCount = 4
                        },
                        new
                        {
                            Id = 33,
                            Description = "Ürün gayet güzel mağazanın hizmeti mükemmel anında hızlı Kargo yapıldı bir gün sonra ürün elime ulaştı paketi de gayet özenliydi teşekkür ederim ",
                            NoCount = 3,
                            ProductId = 23,
                            Star = 5,
                            Title = " KAliteli Hızlı Hizmet",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 34,
                            Description = "Ürüne olumsuz yorum yapanlar tekrar baksın ürün gayet sıkıntısı ve hızlı geldi teşekkürler",
                            NoCount = 2,
                            ProductId = 23,
                            Star = 4,
                            Title = " Hizmet",
                            YesCount = 4
                        },
                        new
                        {
                            Id = 35,
                            Description = "Ürün çok kötü paketlenmiş kutusu ezik geldi",
                            NoCount = 6,
                            ProductId = 23,
                            Star = 3,
                            Title = "Kargo",
                            YesCount = 1
                        },
                        new
                        {
                            Id = 36,
                            Description = "Ürün için biraz çekincelerim vardı ama ürün gayet güzel!!",
                            NoCount = 3,
                            ProductId = 24,
                            Star = 4,
                            Title = "Kalite",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 37,
                            Description = "Çok hızlı ve güvenilir sipariş teşekkürler direnc.net",
                            NoCount = 3,
                            ProductId = 24,
                            Star = 4,
                            Title = "KODLAMA",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 38,
                            Description = "Ürün fotoğraftaki gibi gelmedi almanızı tavsiye etmem ",
                            NoCount = 10,
                            ProductId = 24,
                            Star = 4,
                            Title = "Ürün",
                            YesCount = 2
                        },
                        new
                        {
                            Id = 39,
                            Description = "Cok tereddüt ederek sipariş verdim.Satıcı çok ilgili, ürünün aciliyetini bildirdim, 24 saat dolmadan,eksiksiz ve hızlı bir sekile ulaştı, ürün de gayet ideal, çok beğendim,tesekkürler.. ",
                            NoCount = 3,
                            ProductId = 26,
                            Star = 5,
                            Title = "Hizmet ",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 40,
                            Description = "fiyatina gore iyi bir cihaz. tavsiye ederim",
                            NoCount = 1,
                            ProductId = 26,
                            Star = 3,
                            Title = "Kalite ",
                            YesCount = 4
                        },
                        new
                        {
                            Id = 41,
                            Description = "Ürüne olumsuz yorum yapanlar tekrar baksın ürün gayet sıkıntısı ve hızlı geldi teşekkürler",
                            NoCount = 2,
                            ProductId = 28,
                            Star = 4,
                            Title = " Hizmet",
                            YesCount = 4
                        },
                        new
                        {
                            Id = 42,
                            Description = "Ürün gayet güzel mağazanın hizmeti mükemmel anında hızlı Kargo yapıldı bir gün sonra ürün elime ulaştı paketi de gayet özenliydi teşekkür ederim ",
                            NoCount = 3,
                            ProductId = 28,
                            Star = 5,
                            Title = " KAliteli Hızlı Hizmet",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 43,
                            Description = "Çok hızlı ve güvenilir sipariş teşekkürler direnc.net",
                            NoCount = 2,
                            ProductId = 30,
                            Star = 5,
                            Title = "KODLAMA",
                            YesCount = 3
                        },
                        new
                        {
                            Id = 44,
                            Description = "Çok hızlı ve güvenilir sipariş teşekkürler direnc.net",
                            NoCount = 2,
                            ProductId = 30,
                            Star = 5,
                            Title = "KODLAMA",
                            YesCount = 3
                        },
                        new
                        {
                            Id = 45,
                            Description = "Ürün çok güzel tavsiye ederim",
                            NoCount = 3,
                            ProductId = 32,
                            Star = 5,
                            Title = " Kalite",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 46,
                            Description = "fiyatina gore iyi bir cihaz. tavsiye ederim",
                            NoCount = 1,
                            ProductId = 32,
                            Star = 2,
                            Title = "Kalite ",
                            YesCount = 5
                        },
                        new
                        {
                            Id = 47,
                            Description = "Ürün gayet güzel mağazanın hizmeti mükemmel anında hızlı Kargo yapıldı bir gün sonra ürün elime ulaştı paketi de gayet özenliydi teşekkür ederim ",
                            NoCount = 3,
                            ProductId = 32,
                            Star = 5,
                            Title = " KAliteli Hızlı Hizmet",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 48,
                            Description = "Çok hızlı ve güvenilir sipariş teşekkürler direnc.net",
                            NoCount = 2,
                            ProductId = 36,
                            Star = 5,
                            Title = "KODLAMA",
                            YesCount = 3
                        },
                        new
                        {
                            Id = 49,
                            Description = "ürün çok kötü sakın almayın ",
                            NoCount = 10,
                            ProductId = 36,
                            Star = 5,
                            Title = " Kalite",
                            YesCount = 1
                        },
                        new
                        {
                            Id = 50,
                            Description = "Ürün fotoğraftaki gibi gelmedi almanızı tavsiye etmem ",
                            NoCount = 10,
                            ProductId = 36,
                            Star = 2,
                            Title = "Ürün",
                            YesCount = 2
                        },
                        new
                        {
                            Id = 51,
                            Description = "Cok tereddüt ederek sipariş verdim.Satıcı çok ilgili, ürünün aciliyetini bildirdim, 24 saat dolmadan,eksiksiz ve hızlı bir sekile ulaştı, ürün de gayet ideal, çok beğendim,tesekkürler.. ",
                            NoCount = 3,
                            ProductId = 38,
                            Star = 3,
                            Title = "Hizmet ",
                            YesCount = 8
                        },
                        new
                        {
                            Id = 52,
                            Description = "Ürün gayet güzel mağazanın hizmeti mükemmel anında hızlı Kargo yapıldı bir gün sonra ürün elime ulaştı paketi de gayet özenliydi teşekkür ederim ",
                            NoCount = 4,
                            ProductId = 38,
                            Star = 5,
                            Title = " KAliteli Hızlı Hizmet",
                            YesCount = 12
                        },
                        new
                        {
                            Id = 53,
                            Description = "Cok tereddüt ederek sipariş verdim.Satıcı çok ilgili, ürünün aciliyetini bildirdim, 24 saat dolmadan,eksiksiz ve hızlı bir sekile ulaştı, ürün de gayet ideal, çok beğendim,tesekkürler.. ",
                            NoCount = 5,
                            ProductId = 40,
                            Star = 5,
                            Title = "Hizmet ",
                            YesCount = 2
                        },
                        new
                        {
                            Id = 54,
                            Description = "ürün çok kötü sakın almayın",
                            NoCount = 8,
                            ProductId = 40,
                            Star = 1,
                            Title = "Hizmet ",
                            YesCount = 1
                        });
                });

            modelBuilder.Entity("WebServiceProject.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Currency");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "TL",
                            Value = 1.0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "USD",
                            Value = 6.0999999999999996
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "EURO",
                            Value = 6.6100000000000003
                        });
                });

            modelBuilder.Entity("WebServiceProject.Models.MainCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("MainCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Mikrodenetleyiciler"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Entegreler"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Yarı İletkenler"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Arduino"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Raspberry Pi"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Geliştirme Kartları"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Lcd ve Display"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Sensör ve Modüller"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Kablosuz Haberleşme"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "3D Printer ve CNC"
                        });
                });

            modelBuilder.Entity("WebServiceProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShowcaseProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Property")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategory1Id")
                        .HasColumnType("int");

                    b.Property<int>("SubCategory2Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Description = "Arduino'nun alışageldiğimiz standart boardlarından olan Arduino Uno R3 SMD CH340 Chip'in bu klonundaki temel farklılığı kullandığı programlama entegresinin (USB-Serial dönüştürücü) CH340 olması. Orjinal Arduino'dan birkaç küçük farkı olmasına rağmen kullanımı, yazılımı ve genişletme kartlarının uyumluluğu bakımından hiçbir fark bulunmamaktadır. Bu üründe ve daha birçok elektronik üründe daha da popüler olarak kullanılmaya başlanan CH340 USB - Serial dönüştürücü için, Windows 7 ve Mac OS X kullanıyorsanız driver yüklemeniz gerekmektedir.Windows 7 ve Mac OS X için gereken bu sürücüyü aşağıdaki doküman kısmında bulabilirsiniz.Linux, Windows 8 ve üstü için herhangi bir driver gerekli değildir.Arduino Uno R3 CH340 SMD ile Arduino Uno Dip arasındaki fark mikrodenetleyinin SMD veya DIP olarak ayrılmasının yanı sıra DIP türünün değiştirilebilir olmasıdır.",
                            Image = "img1.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "Klon Arduino Uno R3 SMD",
                            Origin = "China",
                            Price = 17.109999999999999,
                            StockCode = "DSTK0703",
                            SubCategory1Id = 10,
                            SubCategory2Id = 0,
                            Title = "Arduino Uno R3 SMD CH340 Chip - Klon (USB Kablo Dahil)"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            Description = "Raspberry Pi 4 28nm tabanlı 1.5G Dört Çekirdekli CPU ve 4Gb DRR4 RAM içeren küçük bir DIY bilgisayardır. PC benzeri yetenekler elde etmek için Raspberry Pi 4, 4K Mikro HDMI, USB 3.0, BLE Bluetooth 5.0, çift-bantlı 2.4/5.0 GHz Wireless LAN, USB-C güç girişi ve PoE ile uyumlu True Gigabit Ethernet'e sahiptir.Raspberry Pi 4'ün ana yönü daha iyi performanstır; daha iyi VideoCoreVI Graphics ile 1,5 GHz Dört Çekirdekli ARM Cortex-A72 CPU'ya sahiptir. Pi 4, bir 4K 60fps HEVC videosunu bir Micro-HDMI portu üzerinden görüntüleyebilir ve aynı anda iki adet 4K ekrana ancak 30fps yenileme hızıyla bağlanabilir. 1000Mbps True Gigabit Ethernet ve dört USB portu vardır, ancak ikisi USB 2.0 aktarma hızının on katı olan USB 3.0 portlarıdır. Ek olarak, Raspberry Pi 4 yeni bir 5V / 3A güç kaynağı kullanıyor ve daha iyi bir dayanıklılığa sahip olan ve her iki tarafta da çalışabilen bir USB Tip C portu üzerinden bağlanıyor.",
                            Image = "img2.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "Raspberry Pi",
                            Origin = "Raspberry Pi",
                            Price = 448.56,
                            StockCode = "14655",
                            SubCategory1Id = 2,
                            SubCategory2Id = 0,
                            Title = "Raspberry Pi 4 4GB - Model B"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 9,
                            Description = "ESP8266, yeni bağlantılı dünya ihtiyaçları için tasarlanmış oldukça entegre bir çiptir. Uygulamayı barındırabilmesine veya tüm Wi-Fi ağ işlevlerini başka bir uygulama işlemcisinden yönlendirebilmesine olanak tanıyan eksiksiz ve kendine yeten bir Wi-Fi ağ çözümü sunar.ESP8266,çalıştırma süresince minimal ön yükleme ve minimal yükleme ile GPIO'ları aracılığıyla sensörler ve diğer uygulama özellikli cihazlarla entegre olmasını sağlayan güçlü dahili işleme ve depolama yeteneklerine sahiptir. Yüksek derecede on-chip entegrasyonu minimal dış devreye imkan tanır ve ön uç modülü de dahil olmak üzere tüm çözüm minimum PCB alanını alacak şekilde tasarlanmıştır.",
                            Image = "img3.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "Esp8266",
                            Origin = "Espressif",
                            Price = 10.59,
                            StockCode = " DSTK2404",
                            SubCategory1Id = 1,
                            SubCategory2Id = 0,
                            Title = "Esp8266 Seri Wifi Modül"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 16,
                            Description = "Tekli Breadboard, Devre kurmak için en pratik parçalardan olan breadboard ile kolayca prototipleme ve deney yapmak için uygundur. Atlama(jumper) kablolarıyla uyumluluk sağlamaktadır.",
                            Image = "img4.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "Breadboard",
                            Origin = "China",
                            Price = 4.9800000000000004,
                            StockCode = " DSTK3861",
                            SubCategory1Id = 2,
                            SubCategory2Id = 0,
                            Title = "Tekli Breadboard"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            Description = "LattePanda 4G/64GB,  Windows 10  işletim sistemi kullanan bir mini bilgisayar ve geliştirme kartıdır. Arduino kartları ile uyumludur. Türkiye'de en uygun fiyatlarla Direnc.net'te bulabileceğiniz mini bilgisayarda dahili 4GB Ram ve 64GB Harddisk vardır.",
                            Image = "img5.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "LattePanda",
                            Origin = "LattePanda",
                            Price = 1009.0,
                            StockCode = " DFR0419",
                            SubCategory1Id = 1,
                            SubCategory2Id = 0,
                            Title = "LattePanda Windows 10 Lisanssız 4G/64GB"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 10,
                            Description = "Anycubic 4Max Pro tamamen kapalı kasalı, FDM Fused Deposition Modeling yani eriyik yığma modelleme teknolojisine sahip kullanıcı dostu, ısıtma tablalı bir 3D yazıcıdır. 270mm x 205mm x 205 geniş çalışma alanına sahip bu 3 boyutlu yazıcı kullanıcılara otomatik devam özelliği sunmaktadır. Bu sayede güç kesilmesi gibi nedenlerle yarım kalan baskıyı, kaldığı yerden devam ettirebilirsiniz.Otomatik kapanma fonksiyonu ile baskı bittiğinde ürünün otomatik kapanmasını sağlayabilirsiniz.Ayrıca filament sensörü filament bittiğinde yada kırıldığında sizi uyarmaktadır.Anycubic 4Max Pro, ayrı bir kuruluma gerek duymayan,tak çalıştır özellikte,yüksek performanslı bir 3 boyutlu yazıcıdır.",
                            Image = "img6.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "Anycubic 4MAX Pro",
                            Origin = "Anycubic",
                            Price = 3843.0,
                            StockCode = "11152",
                            SubCategory1Id = 1,
                            SubCategory2Id = 0,
                            Title = "Anycubic 4MAX Pro 3D Printer / 3D Yazıcı - Monteli - Beyaz Renk"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Description = "Tip C ve HDMI bağlantısı, 1920 × 1080 piksel, sertleştirilmiş cam kapasitif dokunmatik panel ve güçlü 10000mAh pil içeren evrensel bir taşınabilir dokunmatik monitördür.Raspberry Pi için mükemmel uyumludur ayrıca Jetson Nano gibi diğer popüler mini PC'leri de destekler. Masaüstü bilgisayar, dizüstü bilgisayar, cep telefonu veya oyun konsolu gibi ana cihazlarla basit bir monitör olarak çalışır. C Tipi veya HDMI bağlantısıyla bir saniyede HD büyük ekrana geçebilirsiniz.",
                            Image = "img7.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "Monitör",
                            Origin = "WaveShare",
                            Price = 1375.0,
                            StockCode = " 16549",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "15.6 inç Evrensel Taşınabilir Dokunmatik Full HD, IPS, HDMI LCD"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            Description = "Nextion, insan ve proses, makina, uygulama ya da cihaz arasında kontrol ve görselleştirme arabirimi olarak görev yapan bir Seamless Human Machine Interface (HMI) çözümüdür. Geleneksel LCD ve LED Nixie tübünün yerini almak için tasarlanmış en iyi çözümdür.",
                            Image = "img8.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "Lcd Ekran",
                            Origin = "Nextion",
                            Price = 124.37,
                            StockCode = " NX3224T028",
                            SubCategory1Id = 1,
                            SubCategory2Id = 0,
                            Title = "2.8 Inch Nextion HMI Dokunmatik TFT Lcd Ekran - 4MB Dahili Hafıza"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Atmel ATMEGA128A AU TQFP-64 8 bit 16 MHz Mikrodenetleyici ürünü TQFP-64 kılıfta olup 16 MHz frekansı ile çalışan 8 bit değerinde Mikrodenetleyici Çeşitlerindendir. Üzerinde bulunan 64 pinin 53 adedi I/O yani Giriş Çıkış pinidir.Bellek tipi FLASH olan bu mikrodenetleyiciler 5.5V ile 2.7V besleme aralığında,-40 C° ile + 85 C° sıcaklıkları aralığında çalışmaktadır.",
                            Image = "img9.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "ATMEGA128A-AU",
                            Origin = "Atmel",
                            Price = 14.06,
                            StockCode = " DSTK3408",
                            SubCategory1Id = 2,
                            SubCategory2Id = 0,
                            Title = "ATMEGA128A-AU SMD TQFP-64 8-Bit 16 MHz Mikrodenetleyici"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 9,
                            Description = "Bu ürün, bluetooth iletişim protokolü içinde gömülüdür, sürücüyü yüklemenize gerek yoktur, Windows sistemlerinde kullanılabilir, dos, linux ve diğer grafiksel olmayan işletim sistemlerini de kullanabilirsiniz.Bluetooth adaptörü, masaüstü bilgisayarları,avuçiçi bluetooth pda ve bluetooth gps cihazı ile donatılmış bluetooth özellikli bir dizüstü bilgisayar ile bluetooth seri port profillerini(spp) destekler.Bluetooth spp servis bağlantılarını ve iletişimi desteklerReset tuşu ile kaydedilen eşleştirilmiş cihaz bilgilerini kaldırabilir ve yeni Bluetooth ile eşleştirebilirsiniz.Blue chip bluetooth 2.1 standardını kabul eder.Geliştirilmiş ber hata oranı performansı ve otomatik frekans atlamalı teknoloji etkin ve güvenli iletişim sağlayabilir ve iletişimin kararlılığını ve güvenilirliğini sağlamak için daha güçlü bir anti - karışma kabiliyetine sahiptir.Kullanıcı, 1200bps nm toplam 12 farklı baud hızından(varsayılan 9600, n, 8, 1) at komutu kullanarak ayarlayabilir,ayrıca cihaz için daha kişiselleştirilmiş Bluetooth adı ayarlayabilir.Transmitted güç bluetooth class2 standart, dahili yüksek hassasiyetli PCB basılı anten, istikrarlı iletişim mesafesi 15m kadar uyumlu olabilir ile uyumludur",
                            Image = "img10.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "RS232",
                            Origin = "China",
                            Price = 90.629999999999995,
                            StockCode = " DSTK2359",
                            SubCategory1Id = 3,
                            SubCategory2Id = 0,
                            Title = "RS232 Bluetooth Seri Adaptör"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 18,
                            Description = "mBot Blue Bluetooth Versiyonu Eğitim Robotu IR Uzaktan Kumanda Hediyeli olarak gelmektedir. mBot'un varsayılan programı optimize edilmiştir. mBot'un çalışma durumu yerleşik düğme ile kontrol edilebilir.",
                            Image = "img11.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "mBot V1.1",
                            Origin = "MakeBlock",
                            Price = 529.27999999999997,
                            StockCode = "90053",
                            SubCategory1Id = 1,
                            SubCategory2Id = 0,
                            Title = "mBot V1.1 - Blue - Bluetooth Versiyonu STEM Eğitim Robotu"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 27,
                            Description = "YH 862D Dijital Ayarlı Havya İstasyonu, SMD cihazları tamir eden tamircilerin en çok tercih ettiği havya seti.",
                            Image = "img12.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "YH862D",
                            Origin = "TT-Technich",
                            Price = 406.25,
                            StockCode = "DSTK1985",
                            SubCategory1Id = 3,
                            SubCategory2Id = 0,
                            Title = "YH862D Dijital İstasyonlu Havya"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            Description = "BBC micro:bit, 32 bit ARM Cortex-M0 işlemciyi temel alarak, ivmeölçer ve pusula sensörlerine, Bluetooth Düşük Enerji ve USB bağlantısına, 25 LED'li ekrandan ve iki programlanabilir tuştan oluşur ve USB ya da harici bir pil takımı ile çalıştırılabilir.Cihaz giriş ve çıkışları,21 pinli kenar konnektörünün parçası olan beş halkalı konektör içinden geçmektedir.",
                            Image = "img13.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "BBC Micro",
                            Origin = "micro:bit",
                            Price = 130.0,
                            StockCode = " 9673",
                            SubCategory1Id = 6,
                            SubCategory2Id = 0,
                            Title = "BBC Micro:Bit Geliştirme Kartı"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 15,
                            Description = "SSR-25DA Solid State Röle 25 A değerine kadar kontrol sağlayabilir. Giriş yani tetikleme DC gerilim olmalıdır. Çıkış yani yük AC gerilim olmalıdır. Solid State Rölerin en büyük avantajlarından biri normal röleler gibi mekanik kontaklara sahip olmamasıdır. Bunun yerine Triac kullanır. Ayrıca, optik yalıtımlı ekstra güvenlik sunar.",
                            Image = "img14.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "Arduino ve Raspberry Pi Uyumlu",
                            Origin = "Fotek",
                            Price = 18.440000000000001,
                            StockCode = "DSTK4227",
                            SubCategory1Id = 8,
                            SubCategory2Id = 0,
                            Title = "SSR-25DA (25A) Solid State Röle (Geliştirme Kartlarıyla Uyumlu)"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Bu bir mini trafik lambası modülüdür. Yüksek parlaklık ve kompakt tasarımı ile trafik lamba sistemi için uygun bir Arduino modülüdür. 3 adet pini ve bir ground pini bulunmaktadır. Her ışığın pinine 5V vererek ledleri sıra ile yakabilirsiniz.",
                            Image = "img15.png",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "Arduino LED",
                            Origin = "China",
                            Price = 4.0599999999999996,
                            StockCode = "14114",
                            SubCategory1Id = 5,
                            SubCategory2Id = 1,
                            Title = "Arduino LED Trafik Lambası Modülü"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "IRF1405, N Kanal Mosfet Çeşitlerinden olup TO-220 kılıftadır. IRF1405, N Kanal Power Mosfet türündedir. IRF1405 55Vluk bir Gate-Source gerilimine sahip olup 169A sürekli çıkış akımına sahiptir.",
                            Image = "img16.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "55V, 5.3mohm",
                            Origin = "IR / FAIRCHILD",
                            Price = 4.9800000000000004,
                            StockCode = "DSTK4773",
                            SubCategory1Id = 2,
                            SubCategory2Id = 0,
                            Title = "IRF1405 N Kanal Power Mosfet TO-220"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "RC522 RFID Okuyucu Kartı, NFC frekansı olan 13,56 MHz frekansında çalışan tagler üzerinde okuma ve yazma işlemeni yapabilen, düşük güç tüketimli, ufak boyutlu bir karttır.Arduino başta olmak üzere bir çok mikrodenetleyeci platformu ile beraber rahatlıkla kullanılabilir. 424 kbit / s haberleşme hızına sahiptir.RFID üzerinde farklı şifreleme türlerini desteklemektedir.Desteklediği kart türleri mifare1 S50,mifare1 S70 mifare ultralight,mifare pro ve  mifare desfire'dir. Not: 125 KHz frekansında çalışan RFID kartlarını desteklememektedir.Yalnızca 13,56 MHz frekansında çalışan kartları desteklemektedir.NFC modülleri bu frekansta çalıştığı için NFC kartları ile beraber kullanılabilir.",
                            Image = "img17.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "RFID",
                            Origin = "China",
                            Price = 12.5,
                            StockCode = "DSTK2449",
                            SubCategory1Id = 5,
                            SubCategory2Id = 0,
                            Title = "Rc522 RFID Okuyucu 13.56 Mhz"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 23,
                            Description = "Su Geçirmez Mike Konnektör GX-16 3 pinlidir. Veri sistemleri, bilgisayar, otomasyon, ölçüm-kontrol sistemleri, mekanik ekipmanlarda, ses/video, iletişim, otomotiv ve daha birçok sektörlerde kullanılan Mike Konnektörler, su geçirmez şekilde tasarlanmıştır.",
                            Image = "img18.png",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "Konnektör",
                            Origin = "China",
                            Price = 12.15,
                            StockCode = "15633",
                            SubCategory1Id = 5,
                            SubCategory2Id = 0,
                            Title = "3-Pin Su Geçirmez Mike Konnektör GX-16"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Description = "RAK2245 Pi HAT Sürümü RAK2245 ailesinin en büyüğüdür ancak Raspberry Pi 40pin başlığı ile tam uyumluluk sunar. Ürünün frekans değeri 868 Mhz'dir. Böylece Raspberry Pi'yi özünde kullanan bir DIY ağ geçidi için mükemmel bir çözümdür. Bu, düşük maliyetli ve istikrarlı bir performansla LoRaWAN çözümünün hızlı bir şekilde kullanılmasını sağlar.RAK2245 hattındaki diğer modüllerde olduğu gibi, Semtech 1301 ve çift SX1257 / 58 ön uç yongalarına dayanıyor.Bu ürünün son nesli(RAK831) üzerinde bir takım iyileştirmeler içeren tam teşekküllü bir 8 kanallı LoRa Konsantratörüdür.",
                            Image = "img19.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "RAK2245 Pi",
                            Origin = "China",
                            Price = 1074.0,
                            StockCode = "15878",
                            SubCategory1Id = 2,
                            SubCategory2Id = 0,
                            Title = "RAK2245 Pi HAT Sürümü 868 Mhz"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Neo-7m Mini Gps Modülü Arduino ile uyumlu çalışmaktadır. Bilindiği üzere GPS (Global Positioning System) bir Küresel Konumlama Sistemi'dir. Dünya üzerinde herhangi bir görüş hattında, 4 veya daha fazla uydusu ile her türlü hava koşullarında yer ve zaman bilgilerini sağlayan uzay tabanlı uydu navigasyon sistemidir. ",
                            Image = "img20.jpg",
                            IsActive = true,
                            IsShowcaseProduct = true,
                            Name = "Arduino Shield",
                            Origin = "China",
                            Price = 88.219999999999999,
                            StockCode = "15638",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Neo-7m Arduino Shield Mini Gps Modülü"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "LCD Shield en çok kullanılan Arduino shield çeşitlerindendir. Kart üzerinde 2x16 LCD ekran, 5 adet programlanabilir buton ve bir adet reset butonu vardır. Arduino ile ekranı açıp kapatabilir ve arka ışığı kontrol edebilirsiniz.",
                            Image = "img21.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Arduino Shield",
                            Origin = "China",
                            Price = 14.33,
                            StockCode = "DSTK2124",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Arduino Lcd Shield"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "Motor Shield en çok kullanılan Arduino shield çeşitlerindendir. Kart ile 4 adet DC motor, 2 adet step motor veya 2 adet servo motor kontrol edebilirsiniz. 4.5-36V arası motorlar için kullanılabilir.",
                            Image = "img22.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Motor Shield",
                            Origin = "China",
                            Price = 11.84,
                            StockCode = "DSTK2135",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Arduino Motor Shield - L293D"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Arduino Uno Sensör Shield, Arduino kartları ile birlikte kullanabileceğiniz, kart üzerine birçok giriş çıkışa sahip kullanışlı bir modüldür. Arduino UNO R3 modeli için tasarlanmış olup benzer pin yapısına sahip olan Leonardo veya farklı kartlarla birlikte kullanılabilir.Arduino'nun tüm giriş çıkış pinleri DATA, VCC ve GND sırası ile 3 pin halindedir.Ürüne UART,I2C portları kart üzerinde ayrı olarak yer verilmiştir. Communication Port konektörüyle I2C veya UART olarak ayarlanabilir.Arduino Uno Sensör Shield, Arduino Uno, Leonardo ve Mega modelleriyle kullanılabilir.Ancak bu modellerdeki I2C ve SPI portu farklı pinler üzerinde olduğu için sadece bu portlar kullanılamaz.",
                            Image = "img23.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Sensör Shield",
                            Origin = "China",
                            Price = 9.0299999999999994,
                            StockCode = "DSTK2143",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Arduino Uno Sensör Shield V4.0"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Description = "Arduino Ethernet Shield Arduino ile internete bağlanmanıza olanak sağlar.Sunucu veya istemci olarak kullanılabilir. Lehimlemeye gerek duymadan kolaylıkla Arduino'ya bağlayabilirsiniz. Arduino ethernet kütüphanesi ile uyumludur. SD kart takıp karttaki bilgilere internet üzerinden ulaşabilirsiniz. Arduino Uno ile tam uyumludur. Benzer pin yapısına sahip diğer Arduino modelleri ile de kullanılabilir.",
                            Image = "img24.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Ethernet Shield",
                            Origin = "China",
                            Price = 34.270000000000003,
                            StockCode = "DSTK2084",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Arduino Ethernet Shield"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Description = "Sensör Shield Arduino Nano için özel olarak tasarlanmış olup benzer pin yapısına sahip diğer Arduino'larla da kullanılabilir. Nano ve geliştirme kartlarını yeni kullanmaya başlayanlar için ideal bir Shield kartıdır. Lehimlemeye gerek duymadan kolayca bağlantı yapabilirsiniz.",
                            Image = "img25.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Nano Sensör",
                            Origin = "China",
                            Price = 13.710000000000001,
                            StockCode = "9763",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Arduino Nano Sensör Shield"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            Description = "Arduino Mega Sensör Shield Kartı ürünü Arduino Mega için tasarlanmıştır. Ancak benzer pin yapısına sahip DUE veya diğer kartlar ile kullanılabilir. Shield kartları projelerinizi geliştirirken yaşadığınız I/O eksikliği sorununu çözmek için üretilmiştir. Bu ürün ile sensör servo, röle vb. elemanları kolayca devreye bağlayabilirsiniz. Arduino Mega Sensör Shield kartı ile kompleks devreleriniz daha toplu ve daha profesyonel görünecektir. Ayrıca siz de devre takibini daha kolay yapabilirsiniz.",
                            Image = "img26.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Mega Sensör",
                            Origin = "China",
                            Price = 21.18,
                            StockCode = "9762",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Arduino Mega Sensör Shield"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            Description = "VHM-314, Bluetooth 4.1 teknolojisine kullanan bir Audio modülüdür. Usb girişli, 3.7v lityum pil uyumlu led indikatörlü 3.5 mm stereo jak, kulaklık desteği amfi desteği sağlayan bu modül ile ses projelerinizi rahatlıkla gerçekleştirebilirsiniz.Güç verildiğinde mavi indikatör yanar ve bluetooth moduna girer ve eşleşme için bekler.",
                            Image = "img27.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Bluetooth Audio",
                            Origin = "China",
                            Price = 22.120000000000001,
                            StockCode = "14105",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "VHM-314 Bluetooth Audio Alıcı - Kablosuz Stereo Müzik Modülü"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            Description = "Arduino Touch Shield kartında kullanılan MPR121 entegresi(Proximity Kapasitif Dokunma Sensorü Denetleyici) kapasitif dokunma arayüzlerinin oluşturulmasında mükemmel bir seçenektir ve Touch Shield üzerinde kullanımıyla Arduino projelerinde HMI (human-machine interface) çözümleri için oldukça uygundur. Touch Shield 12 kapsitif touch 'pad'e sahiptir. Bu shield kartı ile toplamda 12 hassas dokunmatik butona sahip olursunuz.Touch Shield üzerindeki lojik seviye dönüştürücü (logic level converter), shield'ın hem 5V hem de 3.3V 'luk Arduino kartlarla çalışmasını sağlar.",
                            Image = "img28.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Touch Shield",
                            Origin = "China",
                            Price = 37.380000000000003,
                            StockCode = "DSTK2093",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Arduino Touch Shield - X"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            Description = "Klemensli Genişletme Kartı Arduino Uno ile tam uyumludur. Benzer pin yapısına sahip diğer Arduino'larla da kullanılabilir. Bağlantıları daha sağlam yapmak için kabloları lehimlemek yerine sökülüp takılabilir şekilde vidali klemans kullanabilmeniz için tasarlanan bu kartta çeşitli sensör ve motorları bağlayabilmeniz için ek terminaller bulunmaktadır.",
                            Image = "img29.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Screw Shield",
                            Origin = "China",
                            Price = 34.270000000000003,
                            StockCode = "DSTK2088",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Arduino Screw Shield Genişleme Kartı"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Description = "Neo-6m Mini Gps Modülü Arduino ile uyumlu çalışmaktadır. Bilindiği üzere GPS (Global Positioning System) bir Küresel Konumlama Sistemi'dir. Dünya üzerinde herhangi bir görüş hattında, 4 veya daha fazla uydusu ile her türlü hava koşullarında yer ve zaman bilgilerini sağlayan uzay tabanlı uydu navigasyon sistemidir.",
                            Image = "img30.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Neo-6m",
                            Origin = "China",
                            Price = 56.07,
                            StockCode = "15637",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Neo-6m Arduino Shield Mini Gps Modülü"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Description = "Neo-7m Mini Gps Modülü Arduino ile uyumlu çalışmaktadır. Bilindiği üzere GPS (Global Positioning System) bir Küresel Konumlama Sistemi'dir. Dünya üzerinde herhangi bir görüş hattında, 4 veya daha fazla uydusu ile her türlü hava koşullarında yer ve zaman bilgilerini sağlayan uzay tabanlı uydu navigasyon sistemidir.",
                            Image = "img31.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Neo-7m",
                            Origin = "China",
                            Price = 74.760000000000005,
                            StockCode = "15638",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Neo-7m Arduino Shield Mini Gps Modülü"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Description = "Neo-m8n Mini Gps Modülü Arduino ile uyumlu çalışmaktadır. Bilindiği üzere GPS (Global Positioning System) bir Küresel Konumlama Sistemi'dir. Dünya üzerinde herhangi bir görüş hattında, 4 veya daha fazla uydusu ile her türlü hava koşullarında yer ve zaman bilgilerini sağlayan uzay tabanlı uydu navigasyon sistemidir.",
                            Image = "img32.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Neo-m8n",
                            Origin = "China",
                            Price = 93.450000000000003,
                            StockCode = "15639",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Neo-m8n Arduino Shield Mini Gps Modülü"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Description = "ESP-32 Ses kiti ESP-32-A1S tabanlı küçük bir audio geliştirme kartıdır. TF kart girişi, kulaklık çıkışı, 2 mikrafon girişi ve 2 hoparlör çıkışı kartın üzerinde mevcuttur. Hızlı geliştirme için uygun olan bu kart akıllı IOT projelerinde, ev sistemlerinde, akıllı hoparlör çözümleri gibi projelerinde kullanılabilir. ",
                            Image = "img33.png",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Esp-32",
                            Origin = "China",
                            Price = 155.75,
                            StockCode = "14104",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Esp-32 Audio Kit - Ses Geliştirme Kartı"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Description = "ESP13 Wifi Shield Kartı ürünü ile Arduino'nuzu kolayca internete bağlayabilir ve web sunucusu oluşturabilirsiniz. Arduino Uno ve Arduino Mega modelleriyle uyumludur. Ürünün kullanımı hakkında daha detaylı bilgi için dökümanlar kısmındaki kullanma kılavuzunu okuyabilirsiniz.",
                            Image = "img34.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "ESP13",
                            Origin = "China",
                            Price = 76.010000000000005,
                            StockCode = "9764",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "ESP13 Wifi Shield"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Description = "Bu GSM - GPS - GPRS Geliştirme Modülünü Arduino ve Raspberry Pi  ile kullanabilirsiniz.Türkiye’de yasal IMEI kaydı bulunan bu modül ile basit Telefon, SMS işlevli uygulamalardan,araç takibi,M2M uygulamaları ve aklınıza gelebilecek tüm GSM / GPS / GPRS işlemleri geliştirebilirsiniz.Üzerindeki 3 ayrı girişten,besleme yapılabilmektedir: DC044 girişinden 5 - 26V ile, 3.7 - 4.2V Lipo / Lion pil ile, Vin girişinden 5 - 26V ile besleme yapılabilmektedir.Yapılacak beslemenin 2A güce sahip olmasına dikkat ediniz.Modül SIM808,AT komutları kullanılarak programlanır.Power düğmesi modülün gücünü açıp kapatır.Power ON durumuna getirilince Power Led yanar.Ayrıca modülü başlatmak için modülün yan tarafındaki butona 2 saniye kadar basılarak aktif hale getirilir ve diğer 3 LED yanar ve bu ledlerden birisi yanıp sönmeye başlar bu da SIM808 çalışmaya başladığı anlamına gelir.SIM yuvası Modülün altında yer almaktadır.GSM, GPS antenleri ve SIM kartı düzgün takıldığı taktirde LED 3 saniyede bir yanıp sönecektir.Bu da Modülün şebekeye bağlandığının işaretidir.Böylece bir çağrı yaptırabilir veya diğer işlemler yaptırabilirsiniz.Titreşim motoru da bulunduran modül 5V ile çalışmakta olup modülün sağ üst köşesinde bulunan pim ile kontrol edilir.Üzerinde Bluetooth da bulunduran SIM808, AT komutları ile kontrol edilir.SIM8080 modülü Arduino ve Raspberry pi ile Rx - Tx ve GND pimleri kullanılarak haberleşme yapılır.Burada dikkat edilecek konu; işlemci sisteminiz 1.25V / 3.3V / 5V kullanıyor ise VMCU pimini bu sistemin 1.25V / 3.3V veya 5V beslemesine bağlamanız gerekir. Zira SIM808 modülü üzerindeki seviye çevirici VMCU ile Rx / Tx pimlerinin bu seviyede çalışmasını sağlar.USB soketi sadece Firmware güncellenmesi için kullanılmaktadır.",
                            Image = "img35.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "SIM808 Arduino",
                            Origin = "Türkiye",
                            Price = 235.24000000000001,
                            StockCode = "DSTK0956",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "SIM808 Arduino - Raspberry Pi GSM - GPS - GPRS Geliştirme Modülü (IMEI No Kayıtlıdır)"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Description = "Mini GSM Modülü Ardino gibi geliştirme kartlarıyla ya da özel projelerinizde kolaylıkla kullanabilmeniz için header çıkışlara sahiptir. Minimal boyutlarıyla bir çok projeye kolayca entegre edilebilir. Diğer modüllere göre daha ucuz olduğu için sıklıkla tercih edilir.",
                            Image = "img36.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Mini GSM/GPRS",
                            Origin = "China",
                            Price = 60.43,
                            StockCode = "13664",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Mini GSM/GPRS Modülü - SIM800L (IMEI Kayıtlı Değildir)"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Description = "GGS01 GSM/GPS Arduino genişletme kartı, üzerindeki Simcom SIM800 GSM, SIM28 GPS Modülü ve Push-Push Simkart yuvası ile birlikte GPRS&GSM şebekesine Arduino ile birlikte bağlatı kurmanızı sağlar.Ürün IMEI numarası Türkiye’de kayıtlı olup, takacağınız SIM kartınız ile internete bağlanmaya,SMS atmaya & almaya,veri ve ses transferi yapmaya hazır bir Arduino genişletme kartıdır.GGS01 GSM / GPS Modül ile GSM uygulamaları ile birlikte konum bilgisi edinme,araç takip uygulamaları,insan - nesne - cihaz takip uygulamaları yapabilirsiniz.",
                            Image = "img37.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Arduino GSM-GPS",
                            Origin = "Türkiye",
                            Price = 654.14999999999998,
                            StockCode = "10433",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Arduino GSM-GPS Shield / Genişletme Kartı (SIM800 - SIM28 - IMEI Kayıtlıdır)"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "Mini Konrol Modülüanalog ve dijital çıkışıyla ultrasonik sensör ve servo motor kontrol edebileceğiniz bir shield kartıdır. Ayrıca I2C girişine LED barı bağlayarak güç girişini izleyebilirsiniz.",
                            Image = "img38.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Atmega32U4",
                            Origin = "China",
                            Price = 90.340000000000003,
                            StockCode = "12694",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Arduino Atmega32U4 Mini Kontrol Modülü"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Description = "GPRS Shiled Simcom'un SIM900 modülünü kullanır. GSM cep telefonu ağını kullanarak iletişim kurmanın pratik bir yoludur. Shield, AT komutları (GSM 07.05, 07.07 ve SIMCOM AT komutları) göndererek UART üzerinden SMS, MMS, GPRS ve ses elde etmenizi sağlar. Kart ayrıca 12 GPIO, 2 PWM, SIM900 modülü ve bir ADC(2V8 logic)'ye sahiptir.",
                            Image = "img39.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "SIM900 GSM/GPRS",
                            Origin = "China",
                            Price = 161.97999999999999,
                            StockCode = "13665",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "SIM900 GSM/GPRS Geliştirme Modülü - Arduino(IMEI Kayıtlı Değildir"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "Bu Arduino Müzik Shield / MP3 Modülü, üzerinde bulunan VS1053B entegresi sayesinde çeşitli müzik formatlarını oynatabilir. Ogg Vorbis/MP3/AAC/WMA/MID formatlarını destekleyen bu entegre SD kartınızda bulunan tüm müzikleri çalabilir. Üzerinde bulunan mikrofondan yada ses giriş kanalından bağlanıp kayıt alabilirsiniz.",
                            Image = "img40.jpg",
                            IsActive = true,
                            IsShowcaseProduct = false,
                            Name = "Müzik Shield",
                            Origin = "China",
                            Price = 61.369999999999997,
                            StockCode = "DSTK7030",
                            SubCategory1Id = 4,
                            SubCategory2Id = 0,
                            Title = "Arduino Müzik Shield / MP3 Modülü (VS1053B)"
                        });
                });

            modelBuilder.Entity("WebServiceProject.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WebServiceProject.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Slider");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "slider1.jpg",
                            IsActive = true,
                            Name = "slider 1"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "slider2.jpg",
                            IsActive = true,
                            Name = "slider 2"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "slider3.jpg",
                            IsActive = true,
                            Name = "slider 3"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "slider4.jpg",
                            IsActive = true,
                            Name = "slider 4"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "slider5.jpg",
                            IsActive = true,
                            Name = "slider 5"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "slider6.jpg",
                            IsActive = true,
                            Name = "slider 6"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "slider7.jpg",
                            IsActive = true,
                            Name = "slider 7"
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "slider8.jpg",
                            IsActive = true,
                            Name = "slider 8"
                        });
                });

            modelBuilder.Entity("WebServiceProject.Models.SubCategory1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.ToTable("SubCategories1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MainCategoryId = 4,
                            Name = "Orijinal Arduino"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MainCategoryId = 4,
                            Name = "Arduino Ana Board"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MainCategoryId = 4,
                            Name = "Arduino Eğitim Setleri"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            MainCategoryId = 4,
                            Name = "Arduino Shield"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            MainCategoryId = 4,
                            Name = "Arduino Sensör ve Modüller"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            MainCategoryId = 4,
                            Name = "Arduino Röle Kartları"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            MainCategoryId = 4,
                            Name = "Arduino Gsm ve Gps"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            MainCategoryId = 4,
                            Name = "Arduino Kitap"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            MainCategoryId = 4,
                            Name = "Arduino Aksesuarları"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            MainCategoryId = 4,
                            Name = "Arduino Lilypard"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            MainCategoryId = 4,
                            Name = "Arduino Lcd Display"
                        });
                });

            modelBuilder.Entity("WebServiceProject.Models.SubCategory2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("SubCategory1Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategory1Id");

                    b.ToTable("SubCategories2");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Arduino Modüller",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Kablosuz Haberleşme",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Su Sensörleri",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Sıcaklık ve Nem Sensörleri",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Gaz ve Basınç Sensörleri",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Mesafe ve Hareket Sensörleri",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Eğim / İvme /Gyro Sensörleri",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Medikal Sensörler",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Renk ve Işık Sensörleri",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Akım ve Voltaj Sensörleri",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Lazer ve Lazerli Sensörler",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "RTC - Gerçek Zamanlı Saat Modülleri",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Ses ve Amfi Modülleri",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Ph Sensörler",
                            SubCategory1Id = 5
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Arduino Sensör Ve Modüller (Tümü)",
                            SubCategory1Id = 5
                        });
                });

            modelBuilder.Entity("WebServiceProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebServiceProject.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("WebServiceProject.Models.SubCategory1", b =>
                {
                    b.HasOne("WebServiceProject.Models.MainCategory", "MainCategory")
                        .WithMany("SubCategory1List")
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebServiceProject.Models.SubCategory2", b =>
                {
                    b.HasOne("WebServiceProject.Models.SubCategory1", "SubCategory1")
                        .WithMany("SubCategory2List")
                        .HasForeignKey("SubCategory1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebServiceProject.Models.UserRole", b =>
                {
                    b.HasOne("WebServiceProject.Models.Role", "Role")
                        .WithMany("UsersRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebServiceProject.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
